function registerPeerUser() {
    echo "Registering peer0"

    export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/org1.deployment.com/

    echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7055-ca-org1-deployment.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7055-ca-org1-deployment.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7055-ca-org1-deployment.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7055-ca-org1-deployment.pem
    OrganizationalUnitIdentifier: orderer' >"${PWD}/organizations/peerOrganizations/org1.deployment.com/msp/config.yaml"

    # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

    # Copy org1's CA cert to org1's /msp/tlscacerts directory (for use in the channel MSP definition)
    mkdir -p "${PWD}/organizations/peerOrganizations/org1.deployment.com/msp/tlscacerts"
    cp "${PWD}/organizations/fabric-ca/org1/ca-cert.pem" "${PWD}/organizations/peerOrganizations/org1.deployment.com/msp/tlscacerts/ca.crt"

    # Copy org1's CA cert to org1's /tlsca directory (for use by clients)
    mkdir -p "${PWD}/organizations/peerOrganizations/org1.deployment.com/tlsca"
    cp "${PWD}/organizations/fabric-ca/org1/ca-cert.pem" "${PWD}/organizations/peerOrganizations/org1.deployment.com/tlsca/tlsca.org1.deployment.com-cert.pem"

    # Copy org1's CA cert to org1's /ca directory (for use by clients)
    mkdir -p "${PWD}/organizations/peerOrganizations/org1.deployment.com/ca"
    cp "${PWD}/organizations/fabric-ca/org1/ca-cert.pem" "${PWD}/organizations/peerOrganizations/org1.deployment.com/ca/ca.org1.deployment.com-cert.pem"

    set -x
    ./bin/fabric-ca-client register --caname ca-org1-deployment --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/org1/ca-cert.pem"
    { set +x; } 2>/dev/null

    echo "Generating the peer0 msp"
    set -x
    # -M and --mspdir both can be used to specify the MSP directory path
    ./bin/fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7055 --caname ca-org1-deployment -M "${PWD}/organizations/peerOrganizations/org1.deployment.com/peers/peer0.org1.deployment.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/org1/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/peerOrganizations/org1.deployment.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/org1.deployment.com/peers/peer0.org1.deployment.com/msp/config.yaml"

    echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
    set -x
    ./bin/fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7055 --caname ca-org1-deployment -M "${PWD}/organizations/peerOrganizations/org1.deployment.com/peers/peer0.org1.deployment.com/tls" --enrollment.profile tls --csr.hosts peer0.org1.deployment.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/org1/ca-cert.pem"
    { set +x; } 2>/dev/null

    # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
    cp "${PWD}/organizations/peerOrganizations/org1.deployment.com/peers/peer0.org1.deployment.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/org1.deployment.com/peers/peer0.org1.deployment.com/tls/ca.crt"
    cp "${PWD}/organizations/peerOrganizations/org1.deployment.com/peers/peer0.org1.deployment.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/org1.deployment.com/peers/peer0.org1.deployment.com/tls/server.crt"
    cp "${PWD}/organizations/peerOrganizations/org1.deployment.com/peers/peer0.org1.deployment.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/org1.deployment.com/peers/peer0.org1.deployment.com/tls/server.key"
}

registerPeerUser
