services:
  - type: web
    name: fabric-ca-org1
    env: docker
    plan: free
    region: oregon
    repo: https://github.com/CyFy-Blockchain/hlf-builder.git
    branch: main
    dockerContext: ./
    envVars:
      - key: FABRIC_CA_HOME
        value: /etc/hyperledger/fabric-ca-server
      - key: FABRIC_CA_SERVER_CA_NAME
        value: ca-org1-deployment
      - key: FABRIC_CA_SERVER_TLS_ENABLED
        value: "true"
      - key: FABRIC_CA_SERVER_PORT
        value: "7055"
      - key: FABRIC_CA_SERVER_DB_TYPE
        value: sqlite3
    autoDeploy: true
